Fix the compatibility with MPForms v5
terminal42/contao-conditionalformfields pull request #70
Opened 2023-01-03 13:19 UTC by qzminski

2023-01-03 13:32 UTC, Toflar commented on composer.json
> +        "contao/core-bundle": "^4.9 || ^5.0",
I mean I know that mp_forms is optional but I think if we release a new minor version with some cleanup and make it at least 4.13, that wouldn't hurt either :)

2023-01-03 13:36 UTC, qzminski commented on composer.json
> +        "contao/core-bundle": "^4.9 || ^5.0",
I did bump to Contao 4.13 now, but not sure if we should touch PHP really. It does not harm to have it for 7.4, too.

2023-01-13 13:49 UTC, Toflar commented
I've released https://github.com/terminal42/contao-mp_forms/releases/tag/5.0.0 so we're good to get this ready as well :)

2023-01-16 08:58 UTC, Toflar requested changes

2023-01-16 08:58 UTC, Toflar commented on composer.json
> +        "terminal42/contao-mp_forms": "^5.0"
```suggestion
        "terminal42/contao-mp_forms": "^4.4 || ^5.0"
```

Otherwise you'll have a hard time installing v4 ;)

2023-01-16 09:24 UTC, Toflar approved these changes

2023-01-16 09:24 UTC, merged